### ISSUE TITLE
UBERON_icdot_mapping_curated.ods as tab delimited file

### ISSUE THREAD

**Issue by wdduncan** [baudisgroup/icdot2uberon#1]
Can you distribute UBERON_icdot_mapping_curated.ods as a tab-delimited file?
I assume (perhaps wrongly) that it is an Open Office spreadsheet, but the tab-delimited format makes it more easily consumable.

**Comment by qingyao** [comment]
Yes, it was edited in LibreOffice. Now exported to a .tsv file of same name.

**Comment by wdduncan** [comment]
Thanks!
